# Generated by Django 2.2.1 on 2019-07-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=400)),
                ('Lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lists')),
            ],
        ),
    ]
