# Generated by Django 2.2.1 on 2019-07-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='emails',
            new_name='txt',
        ),
    ]
