# Generated by Django 2.2.1 on 2019-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190718_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
