# Generated by Django 2.2.1 on 2019-07-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emails_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='complete',
        ),
    ]
