# Generated by Django 2.2.1 on 2019-07-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_emails_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='complete',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
