# Generated by Django 2.2.1 on 2019-07-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_emails_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
