# Generated by Django 2.2.1 on 2019-07-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=400)),
                ('complete', models.BooleanField()),
                ('Lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lists')),
            ],
        ),
    ]
