# Generated by Django 2.2.1 on 2019-08-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='complete',
        ),
    ]
